<?php

namespace CVThequeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AdvertiseRepository extends EntityRepository
{
  public function getSelectList()
  {
    $qb = $this->createQueryBuilder('a')
               ->where('a.published = 1');

    return $qb;
  }

  public function getAdvertisements($numberParPage, $page)
  {
    if ((int) $page < 1) {
        throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
    }

    $query = $this->createQueryBuilder('a')
                  ->leftJoin('a.image', 'i')
                    ->addSelect('i')
                  ->leftJoin('a.category', 'cat')
                    ->addSelect('cat')
                  ->leftJoin('a.advertSkills', 'as')
                    ->addSelect('as')
                  ->where('a.published = 1')
                  ->orderBy('a.created', 'DESC')
                  ->getQuery();

    $query->setFirstResult(($page-1) * $numberParPage)
          ->setMaxResults($numberParPage);

    return new Paginator($query);
  }
}