imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    img_directory: '%kernel.root_dir%/../web/uploads/img'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Activation de l'extension Twig intl
services:
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: MG\UserBundle\Entity\User

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

knp_paginator:
    page_range: 3
    default_options:
        page_name: p
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# fos_user configuration
fos_user:
    from_email:
        address:        noreply@cvtheque.com
        sender_name:    team++
    db_driver: orm 
    firewall_name: main
    user_class: MG\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    
#PUGXMultiUserBundle Configuration            
pugx_multi_user:
    users:
        user_one:
            entity:
                class: MG\UserBundle\Entity\Applicant
                #factory:
            registration:
                form:
                    type: MG\UserBundle\Form\ApplicantRegistrationType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: MGUserBundle:Registration:applicant.form.html.twig
            profile:
                form:
                    type: MG\UserBundle\Form\ApplicantRegistrationEditType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default] 
        user_two:
            entity:
                class: MG\UserBundle\Entity\Society
            registration:
                form:
                    type: MG\UserBundle\Form\SocietyRegistrationType
                template: MGUserBundle:Registration:society.form.html.twig
            profile:
                form:
                    type: MG\UserBundle\Form\SocietyRegistrationEditType
        user_three:
            entity:
                class: MG\UserBundle\Entity\Admin
            registration:
                form:
                    type: MG\UserBundle\Form\AdminRegistrationType
                template: MGUserBundle:Registration:admin.form.html.twig
            profile:
                form:
                    type: MG\UserBundle\Form\AdminRegistrationEditType
                template: MGUserBundle:Profile:admin.edit.form.html.twig