jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        MG\UserBundle\Entity\Applicant: sha512
        MG\UserBundle\Entity\Society: sha512
        MG\UserBundle\Entity\Admin: sha512

    role_hierarchy:
        ROLE_AUTHOR: ROLE_USER
        ROLE_APPLICANT:   [ROLE_AUTHOR, ROLE_USER]
        ROLE_SOCIETY:   [ROLE_AUTHOR, ROLE_USER]
        ROLE_ADMIN:       [ROLE_APPLICANT, ROLE_SOCIETY, ROLE_AUTHOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_APPLICANT, ROLE_SOCIETY, ROLE_MODERATOR, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: /
                check_path: /login_check
                default_target_path: /profile/show
            logout:
                path: /logout
                target: /
            remember_me:
                secret: "%secret%"
                
    #access_control:
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        