# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: MG\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: mg_userbundle_registration }
    app.form.registration.edit:
        class: MG\UserBundle\Form\RegistrationEditType
        tags:
            - { name: form.type, alias: mg_userbundle_registration_edit }
