MG\UserBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        street:
            type: string
            length: 255
        town:
            type: string
            length: '128'
        zipCode:
            type: string
            length: '16'
        country:
            type: string
            length: '8'
    lifecycleCallbacks: {  }
