MG\UserBundle\Entity\Applicant:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\ApplicantRepository
    fields:
        validate:
            type: boolean
        firstname:
            type: string
            length: '32'
        lastname:
            type: string
            length: '32'
        gender:
            type: string
            length: '2'
        birthday:
            type: date
        titleProfile:
            type: string
            length: '128'
    oneToOne:
        cvFile:
            targetEntity: CVFile
            cascade: ["persist", "merge", "remove"]
            joinColumn:
                nullable: true
        logBookFile:
            targetEntity: LogBookFile
            cascade: ["persist", "merge", "remove"]
            joinColumn:
                nullable: true
    oneToMany:
        educations:
            targetEntity: Education
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true

        workExperiences:
            targetEntity: WorkExperience
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true

        skills:
            targetEntity: Skill
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true

        hobbies:
            targetEntity: Hobby
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]
            orphanRemoval: true
    manyToMany:
        advertisements:
            targetEntity: CVThequeBundle\Entity\Advertisement
            inversedBy: applicants
    lifecycleCallbacks: {  }