MG\UserBundle\Entity\Applicant:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\ApplicantRepository
    fields:
        firstname:
            type: string
            length: '32'
        lastname:
            type: string
            length: '32'
        gender:
            type: string
            length: '2'
        birthday:
            type: date
        titleProfile:
            type: string
            length: '128'
    oneToMany:
        educations:
            targetEntity: Education
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]

        workExperiences:
            targetEntity: WorkExperience
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]

        skills:
            targetEntity: Skill
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]

        hobbies:
            targetEntity: Hobby
            mappedBy: applicant
            cascade: ["persist", "merge", "remove"]
    manyToMany:
        advertisements:
            targetEntity: CVThequeBundle\Entity\Advertisement
            inversedBy: applicants
    lifecycleCallbacks: {  }