MG\UserBundle\Entity\LogBookFile:
    type: entity
    table: log_book_file
    repositoryClass: MG\UserBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        extension:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        preRemove: [preRemoveUpload]
        postRemove: [removeUpload]