MG\UserBundle\Entity\Skill:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        applicant:
            targetEntity: Applicant
            inversedBy: skills
    lifecycleCallbacks: {  }
