MG\UserBundle\Entity\Skill:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        applicants:
            targetEntity: Applicant
            inversedBy: skills
            cascade: ["persist", "merge"]
        advertisements:
            targetEntity: CVThequeBundle\Entity\Advertisement
            inversedBy: skills
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }