MG\UserBundle\Entity\Society:
    type: entity
    table: null
    repositoryClass: MG\UserBundle\Repository\SocietyRepository
    fields:
        societyName:
            type: string
            length: 255
        effectif:
            type: integer
        activity:
            type: string
            length: 255
        signatory:
            type: string
            length: 255
        tutor:
            type: string
            length: 255
    lifecycleCallbacks: {  }