mg_applicant_registration:
    path:  /register/applicant
    defaults: { _controller: MGUserBundle:RegistrationApplicant:register }

mg_society_registration:
    path:  /register/society
    defaults: { _controller: MGUserBundle:RegistrationSociety:register }
    
mg_admin_registration:
    path:  /admin/register
    defaults: { _controller: MGUserBundle:RegistrationAdmin:register }
    
fos_user_security:
    resource: "@MGUserBundle/Resources/config/routing/security.xml"
    prefix: /
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

mg_user_show:
    path:     /profile/show
    defaults: { _controller: MGUserBundle:Profile:show }
    
mg_user_profile_visite:
    path:     /profile/show/{slug}
    defaults: { _controller: MGUserBundle:Profile:visite }

mg_user_profile_delete:
    path:     /profile/delete
    defaults: { _controller: MGUserBundle:Profile:delete }

mg_user_profile_picture_edit:
    path:     /profile/picture/edit
    defaults: { _controller: MGUserBundle:Profile:pictureEdit }
    
mg_user_admin_list:
    path:     /admin/user
    defaults: { _controller: "MGUserBundle:User:list" }
    methods:  GET

mg_user_admin_show:
    path:     /admin/user/{id}/show
    defaults: { _controller: "MGUserBundle:User:show" }
    methods:  GET