category:
    resource: "@CVThequeBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category


homepage:
    path:     /
    defaults: { _controller: CVThequeBundle:CVTheque:index }

show_advert:
    path:   advert/show/{slug}
    defaults:  { _controller: CVThequeBundle:Advert:show }

add_advert:
    path:         society/advert/add
    defaults:     { _controller: CVThequeBundle:Advert:add }

update_advert:
    path:         /advertisement/update/{id}
    defaults:     { _controller: CVThequeBundle:Advert:update }
    requirements:
        id:       \d+

delete_advert:
    path:         /advertisement/delete/{id}
    defaults:     { _controller: CVThequeBundle:Advert:delete }
    requirements:
        id:       \d+

admin_advert_show:
    path:         /admin/advert/{page}
    defaults:     { _controller: CVThequeBundle:Advert:listAdvert, page: 1 }
    requirements:
        page:     \d+
